### ISSUE TITLE
IllegalArgumentException when trying to execute sql query in dataset

### ISSUE THREAD

**Issue by tejotes** [kTT/dbunit-extractor#16]
IntelliJ IDEA 2018.1.4 (Ultimate Edition)
Build #IU-181.5087.20, built on May 16, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

DbUnit Extractor Version 1.3

When trying to execute simple SQL-Statement in dataset the following exception occurs:

```
Argument for @NotNull parameter 'htmlContent' of com/intellij/ui/popup/PopupFactoryImpl.createHtmlTextBalloonBuilder must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'htmlContent' of com/intellij/ui/popup/PopupFactoryImpl.createHtmlTextBalloonBuilder must not be null
	at com.intellij.ui.popup.PopupFactoryImpl.$$$reportNull$$$0(PopupFactoryImpl.java)
	at com.intellij.ui.popup.PopupFactoryImpl.createHtmlTextBalloonBuilder(PopupFactoryImpl.java)
	at li.ktt.QueryToXMLConverter$3.run(QueryToXMLConverter.java:302)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kTT** [comment]
Fixed in v1.4
